[versions]
## Android gradle plugin
androidGradlePlugin = "8.7.2"

## AndroidX
# https://developer.android.com/jetpack/androidx/releases/core
androidxCore = "1.13.1"
# https://developer.android.com/jetpack/androidx/releases/appcompat
androidxAppCompat = "1.7.0"
# https://developer.android.com/jetpack/androidx/releases/lifecycle
androidxLifecycle = "2.8.6"
# https://developer.android.com/jetpack/androidx/releases/activity
androidxActivity = "1.9.3"
# https://developer.android.com/jetpack/androidx/releases/datastore
androidxDatastore = "1.1.1"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxNavigation = "2.8.3"
# https://developer.android.com/jetpack/androidx/releases/fragment
androidxFragment = "1.8.4"
# https://developer.android.com/jetpack/androidx/releases/constraintlayout
androidxConstraintlayout = "2.1.4"
# https://developer.android.com/jetpack/androidx/releases/core\
androidxSplashscreen = "1.0.1"

## Compose
# https://developer.android.com/develop/ui/compose/bom/bom-mapping
androidxComposeBom = "2024.12.01"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxComposeNavigation = "2.8.4"

## Amplitude
# https://amplitude.com/docs/sdks/analytics/android
amplitudeAnalytics = "1.16.8"

## Material
material = "1.12.0"

## Kotlin Symbol Processing
# https://github.com/google/ksp/
ksp = "2.0.0-1.0.22"

## Hilt
# https://github.com/google/dagger/releases
hilt = "2.51.1"
# https://developer.android.com/jetpack/androidx/releases/hilt
hiltNavigationCompose = "1.2.0"

## Network
# okhttp
# # https://square.github.io/okhttp/
okhttp = "4.12.0"
# Retrofit
# # https://github.com/square/retrofit
retrofit = "2.11.0"

## Kotlin
# https://github.com/JetBrains/kotlin
kotlin = "2.0.0"
# https://github.com/Kotlin/kotlinx.serialization
kotlinxSerializationJson = "1.7.0"

## Coroutine
# https://github.com/Kotlin/kotlinx.coroutines
coroutine = "1.9.0-RC"

## Test
# https://github.com/junit-team/junit4
junit4 = "4.13.2"
junitJupiter = "5.8.2"

# https://developer.android.com/jetpack/androidx/releases/test
androidxTestRunner = "1.6.2"
androidxTestExt = "1.2.1"
androidxEspresso = "3.6.1"

# https://mockk.io/
mockk = "1.13.11"

# https://github.com/pinterest/ktlint
ktlint = "12.1.1"

## firebase
googleServices = "4.4.2"
firebaseBom = "33.7.0"
crashlytics = "3.0.2"
messaging = "24.1.0"

# https://coil-kt.github.io/coil/#jetpack-compose
coil = "2.7.0"

# https://airbnb.io/lottie/#/android-compose
lottie-compose = "6.5.2"

# https://developers.kakao.com/docs/latest/ko/android/getting-started#apply-sdk
kakao = "2.20.6"

# https://airbnb.io/mavericks/#/setup
mavericks = "3.0.9"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxSplashscreen" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-appcompat-resource = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "androidxAppCompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxComposeNavigation" }
compose-compiler-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlin-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }

androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent", version.ref = "mockk" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }

firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "messaging" }

amplitude-analytics = { module = "com.amplitude:analytics-android", version.ref = "amplitudeAnalytics" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }

kakao-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakao" }

mavericks = { module = "com.airbnb.android:mavericks", version.ref = "mavericks" }
mavericks-compose = { module = "com.airbnb.android:mavericks-compose", version.ref = "mavericks" }
mavericks-hilt = { module = "com.airbnb.android:mavericks-hilt", version.ref = "mavericks" }

[bundles]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
